version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: backend
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: frontend
    command: yarn start
    restart: always
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
